version: "3.8"

services:
  ani_portrait:
    container_name: ani_portrait
    image: maximofn/ani_portrait:1.0.2
    build: .
    runtime: nvidia
    network_mode: "host"
    # volumes:
    #   - ./tts:/root/.local/share/tts
    tty: true
    stdin_open: true
